version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_c
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf # Mount nginx.conf
      - ./typeScoreApi:/var/www/api
    ports:
      - 127.0.0.1:${DOCKER_NGINX_PORT}:80
    depends_on:
      - api

  api:  # Symfony backend
    build: 
      context: ./typeScoreApi
      dockerfile: Dockerfile
    container_name: api_c
    volumes:
      - ./typeScoreApi:/var/www/api
    working_dir: /var/www/api
    ports:
      - "8000:9000" 

  typeScore_db:
    image: mysql:latest
    container_name: typeScore_db_c
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - typescoreapi_typeScore_db_data:/var/lib/mysql
    ports:
      - 127.0.0.1:${DOCKER_DATABASE_PORT}:3306


volumes:
  typescoreapi_typeScore_db_data:
    external: true
